### ISSUE TITLE
merge to upstream project

### ISSUE THREAD

**Issue by christianrauch** [walac/blender-wayland#2]
@walac Great work on the Wayland backend!

I am wondering, did you try to upstream the Wayland backend?

**Comment by xorgy** [comment]
Even if this worked when it was published; it seems like there may be a lot of work involved in bringing this up to date with upstream Blender, seeing as the last commit is from roughly six years ago.

I think there are probably also some open questions about pointer warping. As far as I'm aware, support for proper pointer warping (a core part of Blender) is still not standardized on Wayland. I don't think the pointer confinement protocol is capable of warping, even within the confined region.

**Comment by walac** [comment]
It has been many years since I last worked on it. The project was far from ready to merge at that time, iirc. Things probably are worse then. I can come back to this work when I have time if there is interest (my guess is that it is easier just to start over with a recent version of Wayland and Blender code base).

**Comment by christianrauch** [comment]
I am currently looking into porting this to the upstream master, also replacing the deprecated `wl_shell` with the new `xdg_shell` protocol.

@xorgy Regarding the pointer warping, might the [`relative_pointer_unstable_v1`](https://gitlab.freedesktop.org/wayland/wayland-protocols/blob/master/unstable/relative-pointer/relative-pointer-unstable-v1.xml) protocol help with this?

In any case, I think it would be useful to merge Wayland support upstream, even if some features are not supported yet. It would be deactivated by default, but it would be easier to make changes to the codebase, once it's synchronised with the upstream project.

**Comment by xorgy** [comment]
> Regarding the pointer warping, might the [`relative_pointer_unstable_v1`](https://gitlab.freedesktop.org/wayland/wayland-protocols/blob/master/unstable/relative-pointer/relative-pointer-unstable-v1.xml) protocol help with this?

It gets the functional part of it, but Blender actually carefully warps your pointer to specific positions, and leaves it where it was when you were finished; switching to relative pointer input would be a considerable difference in the user experience. It may be an acceptable substitute, but certainly it'd be jarring to me.

**Comment by christianrauch** [comment]
I managed to rebase the patches on version 2.79 with small changes in the API. However, for rebasing on master, there are many more changes in the GHOST API and I basically started an implementation from scratch.
I will later have a look into the pointer warping problem. I imagine that other applications need the same functionality. Maybe Qt or GTK have this already implemented in some way using this `relative_pointer` protocol.

**Comment by xorgy** [comment]
> I imagine that other applications need the same functionality. Maybe Qt or GTK have this already implemented in some way using this `relative_pointer` protocol.

The way that Blender uses pointer warping is special, most applications used pointer warping only to get relative input. Blender wraps your pointer position around, like asteroids, rather than freezing it in place (which is what relative input usually entails) or trapping it in a box (what confinement is for).

Depending on how [the confinement protocol's `set_cursor_position_hint`](https://github.com/wayland-project/wayland-protocols/blob/master/unstable/pointer-constraints/pointer-constraints-unstable-v1.xml#L218) is implemented in practice, it may be possible to get the desired behaviour with that.

**Comment by christianrauch** [comment]
The Wayland frontend for Blender has been merged upstream (https://developer.blender.org/D6567). Let me know if you have issues with this implementation.
